using System;
using Microsoft.EntityFrameworkCore.Migrations;

namespace Database.Migrations
{
    public partial class V01_InitialCreate : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "guilds",
                columns: table => new
                {
                    id = table.Column<string>(type: "character varying(19)", maxLength: 19, nullable: false),
                    prefix = table.Column<string>(type: "character varying(10)", maxLength: 10, nullable: false),
                    language = table.Column<string>(type: "text", nullable: false),
                    disablenaturalprefix = table.Column<bool>(name: "disable-natural-prefix", type: "boolean", nullable: false),
                    disabledcommands = table.Column<string[]>(name: "disabled-commands", type: "character varying(32)[]", nullable: false),
                    afkrole = table.Column<string>(name: "afk.role", type: "character varying(19)", maxLength: 19, nullable: true),
                    afkprefix = table.Column<string>(name: "afk.prefix", type: "character varying(32)", maxLength: 32, nullable: true),
                    afkprefixforce = table.Column<bool>(name: "afk.prefix-force", type: "boolean", nullable: false),
                    customcommands = table.Column<string>(name: "custom-commands", type: "jsonb", nullable: false),
                    permissionsusers = table.Column<string>(name: "permissions.users", type: "jsonb", nullable: false),
                    permissionsroles = table.Column<string>(name: "permissions.roles", type: "jsonb", nullable: false),
                    channelsannouncements = table.Column<string>(name: "channels.announcements", type: "character varying(19)", maxLength: 19, nullable: true),
                    channelsgreeting = table.Column<string>(name: "channels.greeting", type: "character varying(19)", maxLength: 19, nullable: true),
                    channelsfarewell = table.Column<string>(name: "channels.farewell", type: "character varying(19)", maxLength: 19, nullable: true),
                    channelsspam = table.Column<string>(name: "channels.spam", type: "character varying(19)", maxLength: 19, nullable: true),
                    channelslogsmoderation = table.Column<string>(name: "channels.logs.moderation", type: "character varying(19)", maxLength: 19, nullable: true),
                    channelslogsimage = table.Column<string>(name: "channels.logs.image", type: "character varying(19)", maxLength: 19, nullable: true),
                    channelslogsmemberadd = table.Column<string>(name: "channels.logs.member-add", type: "character varying(19)", maxLength: 19, nullable: true),
                    channelslogsmemberremove = table.Column<string>(name: "channels.logs.member-remove", type: "character varying(19)", maxLength: 19, nullable: true),
                    channelslogsmembernicknameupdate = table.Column<string>(name: "channels.logs.member-nickname-update", type: "character varying(19)", maxLength: 19, nullable: true),
                    channelslogsmemberusernameupdate = table.Column<string>(name: "channels.logs.member-username-update", type: "character varying(19)", maxLength: 19, nullable: true),
                    channelslogsmemberrolesupdate = table.Column<string>(name: "channels.logs.member-roles-update", type: "character varying(19)", maxLength: 19, nullable: true),
                    channelslogsmessagedelete = table.Column<string>(name: "channels.logs.message-delete", type: "character varying(19)", maxLength: 19, nullable: true),
                    channelslogsmessagedeletensfw = table.Column<string>(name: "channels.logs.message-delete-nsfw", type: "character varying(19)", maxLength: 19, nullable: true),
                    channelslogsmessageupdate = table.Column<string>(name: "channels.logs.message-update", type: "character varying(19)", maxLength: 19, nullable: true),
                    channelslogsmessageupdatensfw = table.Column<string>(name: "channels.logs.message-update-nsfw", type: "character varying(19)", maxLength: 19, nullable: true),
                    channelslogsprune = table.Column<string>(name: "channels.logs.prune", type: "character varying(19)", maxLength: 19, nullable: true),
                    channelslogsreaction = table.Column<string>(name: "channels.logs.reaction", type: "character varying(19)", maxLength: 19, nullable: true),
                    channelslogsrolecreate = table.Column<string>(name: "channels.logs.role-create", type: "character varying(19)", maxLength: 19, nullable: true),
                    channelslogsroleupdate = table.Column<string>(name: "channels.logs.role-update", type: "character varying(19)", maxLength: 19, nullable: true),
                    channelslogsroledelete = table.Column<string>(name: "channels.logs.role-delete", type: "character varying(19)", maxLength: 19, nullable: true),
                    channelslogschannelcreate = table.Column<string>(name: "channels.logs.channel-create", type: "character varying(19)", maxLength: 19, nullable: true),
                    channelslogschannelupdate = table.Column<string>(name: "channels.logs.channel-update", type: "character varying(19)", maxLength: 19, nullable: true),
                    channelslogschanneldelete = table.Column<string>(name: "channels.logs.channel-delete", type: "character varying(19)", maxLength: 19, nullable: true),
                    channelslogsemojicreate = table.Column<string>(name: "channels.logs.emoji-create", type: "character varying(19)", maxLength: 19, nullable: true),
                    channelslogsemojiupdate = table.Column<string>(name: "channels.logs.emoji-update", type: "character varying(19)", maxLength: 19, nullable: true),
                    channelslogsemojidelete = table.Column<string>(name: "channels.logs.emoji-delete", type: "character varying(19)", maxLength: 19, nullable: true),
                    channelslogsserverupdate = table.Column<string>(name: "channels.logs.server-update", type: "character varying(19)", maxLength: 19, nullable: true),
                    channelsignoreall = table.Column<string[]>(name: "channels.ignore.all", type: "character varying(19)[]", nullable: false),
                    channelsignoremessageedit = table.Column<string[]>(name: "channels.ignore.message-edit", type: "character varying(19)[]", nullable: false),
                    channelsignoremessagedelete = table.Column<string[]>(name: "channels.ignore.message-delete", type: "character varying(19)[]", nullable: false),
                    channelsignorereactionadd = table.Column<string[]>(name: "channels.ignore.reaction-add", type: "character varying(19)[]", nullable: false),
                    commandautodelete = table.Column<string>(name: "command-auto-delete", type: "jsonb", nullable: false),
                    disabledchannels = table.Column<string[]>(name: "disabled-channels", type: "character varying(19)[]", nullable: false),
                    disabledcommandschannels = table.Column<string>(name: "disabled-commands-channels", type: "jsonb", nullable: false),
                    eventsbanadd = table.Column<bool>(name: "events.ban-add", type: "boolean", nullable: false),
                    eventsbanremove = table.Column<bool>(name: "events.ban-remove", type: "boolean", nullable: false),
                    eventstwemojireactions = table.Column<bool>(name: "events.twemoji-reactions", type: "boolean", nullable: false),
                    messagesfarewell = table.Column<string>(name: "messages.farewell", type: "character varying(2000)", maxLength: 2000, nullable: true),
                    messagesfarewellautodelete = table.Column<long>(name: "messages.farewell-auto-delete", type: "bigint", nullable: true),
                    messagesgreeting = table.Column<string>(name: "messages.greeting", type: "character varying(2000)", maxLength: 2000, nullable: true),
                    messagesgreetingautodelete = table.Column<long>(name: "messages.greeting-auto-delete", type: "bigint", nullable: true),
                    messagesjoindm = table.Column<string>(name: "messages.join-dm", type: "character varying(1500)", maxLength: 1500, nullable: true),
                    messagesignorechannels = table.Column<string[]>(name: "messages.ignore-channels", type: "character varying(19)[]", nullable: false),
                    messagesannouncementembed = table.Column<bool>(name: "messages.announcement-embed", type: "boolean", nullable: false),
                    messagesmoderationdm = table.Column<bool>(name: "messages.moderation-dm", type: "boolean", nullable: false),
                    messagesmoderationreasondisplay = table.Column<bool>(name: "messages.moderation-reason-display", type: "boolean", nullable: false),
                    messagesmoderationmessagedisplay = table.Column<bool>(name: "messages.moderation-message-display", type: "boolean", nullable: false),
                    messagesmoderationautodelete = table.Column<bool>(name: "messages.moderation-auto-delete", type: "boolean", nullable: false),
                    messagesmoderatornamedisplay = table.Column<bool>(name: "messages.moderator-name-display", type: "boolean", nullable: false),
                    messagesautodeleteignoredall = table.Column<bool>(name: "messages.auto-delete.ignored-all", type: "boolean", nullable: false),
                    messagesautodeleteignoredroles = table.Column<string[]>(name: "messages.auto-delete.ignored-roles", type: "character varying(19)[]", nullable: false),
                    messagesautodeleteignoredchannels = table.Column<string[]>(name: "messages.auto-delete.ignored-channels", type: "character varying(19)[]", nullable: false),
                    messagesautodeleteignoredcommands = table.Column<string[]>(name: "messages.auto-delete.ignored-commands", type: "character varying(32)[]", nullable: false),
                    stickyroles = table.Column<string>(name: "sticky-roles", type: "jsonb", nullable: false),
                    reactionroles = table.Column<string>(name: "reaction-roles", type: "jsonb", nullable: false),
                    rolesadmin = table.Column<string[]>(name: "roles.admin", type: "character varying(19)[]", nullable: false),
                    rolesauto = table.Column<string>(name: "roles.auto", type: "jsonb", nullable: false),
                    rolesinitial = table.Column<string>(name: "roles.initial", type: "character varying(19)", maxLength: 19, nullable: true),
                    rolesinitialhumans = table.Column<string>(name: "roles.initial-humans", type: "character varying(19)", maxLength: 19, nullable: true),
                    rolesinitialbots = table.Column<string>(name: "roles.initial-bots", type: "character varying(19)", maxLength: 19, nullable: true),
                    rolesmoderator = table.Column<string[]>(name: "roles.moderator", type: "character varying(19)[]", nullable: false),
                    rolesmuted = table.Column<string>(name: "roles.muted", type: "character varying(19)", maxLength: 19, nullable: true),
                    rolesrestrictedreaction = table.Column<string>(name: "roles.restricted-reaction", type: "character varying(19)", maxLength: 19, nullable: true),
                    rolesrestrictedembed = table.Column<string>(name: "roles.restricted-embed", type: "character varying(19)", maxLength: 19, nullable: true),
                    rolesrestrictedemoji = table.Column<string>(name: "roles.restricted-emoji", type: "character varying(19)", maxLength: 19, nullable: true),
                    rolesrestrictedattachment = table.Column<string>(name: "roles.restricted-attachment", type: "character varying(19)", maxLength: 19, nullable: true),
                    rolesrestrictedvoice = table.Column<string>(name: "roles.restricted-voice", type: "character varying(19)", maxLength: 19, nullable: true),
                    rolespublic = table.Column<string[]>(name: "roles.public", type: "character varying(19)[]", nullable: false),
                    rolesremoveinitial = table.Column<bool>(name: "roles.remove-initial", type: "boolean", nullable: false),
                    rolesdj = table.Column<string[]>(name: "roles.dj", type: "character varying(19)[]", nullable: false),
                    rolessubscriber = table.Column<string>(name: "roles.subscriber", type: "character varying(19)", maxLength: 19, nullable: true),
                    rolesuniquerolesets = table.Column<string>(name: "roles.unique-role-sets", type: "jsonb", nullable: false),
                    selfmodattachmentsenabled = table.Column<bool>(name: "selfmod.attachments.enabled", type: "boolean", nullable: false),
                    selfmodattachmentsignoredroles = table.Column<string[]>(name: "selfmod.attachments.ignored-roles", type: "character varying(19)[]", nullable: false),
                    selfmodattachmentsignoredchannels = table.Column<string[]>(name: "selfmod.attachments.ignored-channels", type: "character varying(19)[]", nullable: false),
                    selfmodattachmentssoftaction = table.Column<short>(name: "selfmod.attachments.soft-action", type: "smallint", nullable: false),
                    selfmodattachmentshardaction = table.Column<short>(name: "selfmod.attachments.hard-action", type: "smallint", nullable: false),
                    selfmodattachmentshardactionduration = table.Column<long>(name: "selfmod.attachments.hard-action-duration", type: "bigint", nullable: true),
                    selfmodattachmentsthresholdmaximum = table.Column<short>(name: "selfmod.attachments.threshold-maximum", type: "smallint", nullable: false),
                    selfmodattachmentsthresholdduration = table.Column<int>(name: "selfmod.attachments.threshold-duration", type: "integer", nullable: false),
                    selfmodcapitalsenabled = table.Column<bool>(name: "selfmod.capitals.enabled", type: "boolean", nullable: false),
                    selfmodcapitalsignoredroles = table.Column<string[]>(name: "selfmod.capitals.ignored-roles", type: "character varying(19)[]", nullable: false),
                    selfmodcapitalsignoredchannels = table.Column<string[]>(name: "selfmod.capitals.ignored-channels", type: "character varying(19)[]", nullable: false),
                    selfmodcapitalsminimum = table.Column<short>(name: "selfmod.capitals.minimum", type: "smallint", nullable: false),
                    selfmodcapitalsmaximum = table.Column<short>(name: "selfmod.capitals.maximum", type: "smallint", nullable: false),
                    selfmodcapitalssoftaction = table.Column<short>(name: "selfmod.capitals.soft-action", type: "smallint", nullable: false),
                    selfmodcapitalshardaction = table.Column<short>(name: "selfmod.capitals.hard-action", type: "smallint", nullable: false),
                    selfmodcapitalshardactionduration = table.Column<long>(name: "selfmod.capitals.hard-action-duration", type: "bigint", nullable: true),
                    selfmodcapitalsthresholdmaximum = table.Column<short>(name: "selfmod.capitals.threshold-maximum", type: "smallint", nullable: false),
                    selfmodcapitalsthresholdduration = table.Column<int>(name: "selfmod.capitals.threshold-duration", type: "integer", nullable: false),
                    selfmodlinksenabled = table.Column<bool>(name: "selfmod.links.enabled", type: "boolean", nullable: false),
                    selfmodlinksallowed = table.Column<string[]>(name: "selfmod.links.allowed", type: "character varying(128)[]", nullable: false),
                    selfmodlinksignoredroles = table.Column<string[]>(name: "selfmod.links.ignored-roles", type: "character varying(19)[]", nullable: false),
                    selfmodlinksignoredchannels = table.Column<string[]>(name: "selfmod.links.ignored-channels", type: "character varying(19)[]", nullable: false),
                    selfmodlinkssoftaction = table.Column<short>(name: "selfmod.links.soft-action", type: "smallint", nullable: false),
                    selfmodlinkshardaction = table.Column<short>(name: "selfmod.links.hard-action", type: "smallint", nullable: false),
                    selfmodlinkshardactionduration = table.Column<long>(name: "selfmod.links.hard-action-duration", type: "bigint", nullable: true),
                    selfmodlinksthresholdmaximum = table.Column<short>(name: "selfmod.links.threshold-maximum", type: "smallint", nullable: false),
                    selfmodlinksthresholdduration = table.Column<int>(name: "selfmod.links.threshold-duration", type: "integer", nullable: false),
                    selfmodmessagesenabled = table.Column<bool>(name: "selfmod.messages.enabled", type: "boolean", nullable: false),
                    selfmodmessagesignoredroles = table.Column<string[]>(name: "selfmod.messages.ignored-roles", type: "character varying(19)[]", nullable: false),
                    selfmodmessagesignoredchannels = table.Column<string[]>(name: "selfmod.messages.ignored-channels", type: "character varying(19)[]", nullable: false),
                    selfmodmessagesmaximum = table.Column<short>(name: "selfmod.messages.maximum", type: "smallint", nullable: false),
                    selfmodmessagesqueuesize = table.Column<short>(name: "selfmod.messages.queue-size", type: "smallint", nullable: false),
                    selfmodmessagessoftaction = table.Column<short>(name: "selfmod.messages.soft-action", type: "smallint", nullable: false),
                    selfmodmessageshardaction = table.Column<short>(name: "selfmod.messages.hard-action", type: "smallint", nullable: false),
                    selfmodmessageshardactionduration = table.Column<long>(name: "selfmod.messages.hard-action-duration", type: "bigint", nullable: true),
                    selfmodmessagesthresholdmaximum = table.Column<short>(name: "selfmod.messages.threshold-maximum", type: "smallint", nullable: false),
                    selfmodmessagesthresholdduration = table.Column<int>(name: "selfmod.messages.threshold-duration", type: "integer", nullable: false),
                    selfmodnewlinesenabled = table.Column<bool>(name: "selfmod.newlines.enabled", type: "boolean", nullable: false),
                    selfmodnewlinesignoredroles = table.Column<string[]>(name: "selfmod.newlines.ignored-roles", type: "character varying(19)[]", nullable: false),
                    selfmodnewlinesignoredchannels = table.Column<string[]>(name: "selfmod.newlines.ignored-channels", type: "character varying(19)[]", nullable: false),
                    selfmodnewlinesmaximum = table.Column<short>(name: "selfmod.newlines.maximum", type: "smallint", nullable: false),
                    selfmodnewlinessoftaction = table.Column<short>(name: "selfmod.newlines.soft-action", type: "smallint", nullable: false),
                    selfmodnewlineshardaction = table.Column<short>(name: "selfmod.newlines.hard-action", type: "smallint", nullable: false),
                    selfmodnewlineshardactionduration = table.Column<long>(name: "selfmod.newlines.hard-action-duration", type: "bigint", nullable: true),
                    selfmodnewlinesthresholdmaximum = table.Column<short>(name: "selfmod.newlines.threshold-maximum", type: "smallint", nullable: false),
                    selfmodnewlinesthresholdduration = table.Column<int>(name: "selfmod.newlines.threshold-duration", type: "integer", nullable: false),
                    selfmodinvitesenabled = table.Column<bool>(name: "selfmod.invites.enabled", type: "boolean", nullable: false),
                    selfmodinvitesignoredcodes = table.Column<string[]>(name: "selfmod.invites.ignored-codes", type: "character varying[]", nullable: false),
                    selfmodinvitesignoredguilds = table.Column<string[]>(name: "selfmod.invites.ignored-guilds", type: "character varying(19)[]", nullable: false),
                    selfmodinvitesignoredroles = table.Column<string[]>(name: "selfmod.invites.ignored-roles", type: "character varying(19)[]", nullable: false),
                    selfmodinvitesignoredchannels = table.Column<string[]>(name: "selfmod.invites.ignored-channels", type: "character varying(19)[]", nullable: false),
                    selfmodinvitessoftaction = table.Column<short>(name: "selfmod.invites.soft-action", type: "smallint", nullable: false),
                    selfmodinviteshardaction = table.Column<short>(name: "selfmod.invites.hard-action", type: "smallint", nullable: false),
                    selfmodinviteshardactionduration = table.Column<long>(name: "selfmod.invites.hard-action-duration", type: "bigint", nullable: true),
                    selfmodinvitesthresholdmaximum = table.Column<short>(name: "selfmod.invites.threshold-maximum", type: "smallint", nullable: false),
                    selfmodinvitesthresholdduration = table.Column<int>(name: "selfmod.invites.threshold-duration", type: "integer", nullable: false),
                    selfmodfilterenabled = table.Column<bool>(name: "selfmod.filter.enabled", type: "boolean", nullable: false),
                    selfmodfilterraw = table.Column<string[]>(name: "selfmod.filter.raw", type: "character varying(32)[]", nullable: false),
                    selfmodfilterignoredroles = table.Column<string[]>(name: "selfmod.filter.ignored-roles", type: "character varying(19)[]", nullable: false),
                    selfmodfilterignoredchannels = table.Column<string[]>(name: "selfmod.filter.ignored-channels", type: "character varying(19)[]", nullable: false),
                    selfmodfiltersoftaction = table.Column<short>(name: "selfmod.filter.soft-action", type: "smallint", nullable: false),
                    selfmodfilterhardaction = table.Column<short>(name: "selfmod.filter.hard-action", type: "smallint", nullable: false),
                    selfmodfilterhardactionduration = table.Column<long>(name: "selfmod.filter.hard-action-duration", type: "bigint", nullable: true),
                    selfmodfilterthresholdmaximum = table.Column<short>(name: "selfmod.filter.threshold-maximum", type: "smallint", nullable: false),
                    selfmodfilterthresholdduration = table.Column<int>(name: "selfmod.filter.threshold-duration", type: "integer", nullable: false),
                    selfmodreactionsenabled = table.Column<bool>(name: "selfmod.reactions.enabled", type: "boolean", nullable: false),
                    selfmodreactionsignoredroles = table.Column<string[]>(name: "selfmod.reactions.ignored-roles", type: "character varying(19)[]", nullable: false),
                    selfmodreactionsignoredchannels = table.Column<string[]>(name: "selfmod.reactions.ignored-channels", type: "character varying(19)[]", nullable: false),
                    selfmodreactionsmaximum = table.Column<short>(name: "selfmod.reactions.maximum", type: "smallint", nullable: false),
                    selfmodreactionsallowed = table.Column<string[]>(name: "selfmod.reactions.allowed", type: "character varying(128)[]", nullable: false),
                    selfmodreactionsblocked = table.Column<string[]>(name: "selfmod.reactions.blocked", type: "character varying(128)[]", nullable: false),
                    selfmodreactionssoftaction = table.Column<short>(name: "selfmod.reactions.soft-action", type: "smallint", nullable: false),
                    selfmodreactionshardaction = table.Column<short>(name: "selfmod.reactions.hard-action", type: "smallint", nullable: false),
                    selfmodreactionshardactionduration = table.Column<long>(name: "selfmod.reactions.hard-action-duration", type: "bigint", nullable: true),
                    selfmodreactionsthresholdmaximum = table.Column<short>(name: "selfmod.reactions.threshold-maximum", type: "smallint", nullable: false),
                    selfmodreactionsthresholdduration = table.Column<int>(name: "selfmod.reactions.threshold-duration", type: "integer", nullable: false),
                    selfmodignoredchannels = table.Column<string[]>(name: "selfmod.ignored-channels", type: "character varying(19)[]", nullable: false),
                    nomentionspamenabled = table.Column<bool>(name: "no-mention-spam.enabled", type: "boolean", nullable: false),
                    nomentionspamalerts = table.Column<bool>(name: "no-mention-spam.alerts", type: "boolean", nullable: false),
                    nomentionspammentionsallowed = table.Column<short>(name: "no-mention-spam.mentions-allowed", type: "smallint", nullable: false),
                    nomentionspamtimeperiod = table.Column<int>(name: "no-mention-spam.time-period", type: "integer", nullable: false),
                    socialenabled = table.Column<bool>(name: "social.enabled", type: "boolean", nullable: false),
                    socialachieverole = table.Column<string>(name: "social.achieve-role", type: "text", nullable: true),
                    socialachievelevel = table.Column<string>(name: "social.achieve-level", type: "text", nullable: true),
                    socialachievechannel = table.Column<string>(name: "social.achieve-channel", type: "character varying(19)", maxLength: 19, nullable: true),
                    socialachievemultiple = table.Column<short>(name: "social.achieve-multiple", type: "smallint", nullable: false),
                    socialmultiplier = table.Column<decimal>(name: "social.multiplier", type: "numeric", nullable: false),
                    socialignoredchannels = table.Column<string[]>(name: "social.ignored-channels", type: "character varying(19)[]", nullable: false),
                    socialignoredroles = table.Column<string[]>(name: "social.ignored-roles", type: "character varying(19)[]", nullable: false),
                    starboardchannel = table.Column<string>(name: "starboard.channel", type: "character varying(19)", maxLength: 19, nullable: true),
                    starboardemoji = table.Column<string>(name: "starboard.emoji", type: "character varying(75)", maxLength: 75, nullable: false),
                    starboardignoredchannels = table.Column<string[]>(name: "starboard.ignored-channels", type: "character varying(19)[]", nullable: false),
                    starboardminimum = table.Column<short>(name: "starboard.minimum", type: "smallint", nullable: false),
                    starboardselfstar = table.Column<bool>(name: "starboard.self-star", type: "boolean", nullable: false),
                    starboardmaximumage = table.Column<long>(name: "starboard.maximum-age", type: "bigint", nullable: true),
                    triggeralias = table.Column<string>(name: "trigger.alias", type: "jsonb", nullable: false),
                    triggerincludes = table.Column<string>(name: "trigger.includes", type: "jsonb", nullable: false),
                    musicdefaultvolume = table.Column<short>(name: "music.default-volume", type: "smallint", nullable: false),
                    musicmaximumduration = table.Column<int>(name: "music.maximum-duration", type: "integer", nullable: false),
                    musicmaximumentriesperuser = table.Column<short>(name: "music.maximum-entries-per-user", type: "smallint", nullable: false),
                    musicallowstreams = table.Column<bool>(name: "music.allow-streams", type: "boolean", nullable: false),
                    musicallowedvoicechannels = table.Column<string[]>(name: "music.allowed-voice-channels", type: "character varying(19)[]", nullable: false),
                    musicallowedroles = table.Column<string[]>(name: "music.allowed-roles", type: "character varying(19)[]", nullable: false),
                    notificationsstreamstwitchstreamers = table.Column<string>(name: "notifications.streams.twitch.streamers", type: "jsonb", nullable: false),
                    notificationsyoutubeuploadchannel = table.Column<string>(name: "notifications.youtube.upload.channel", type: "character varying(19)", nullable: true),
                    notificationsyoutubeuploadmessage = table.Column<string>(name: "notifications.youtube.upload.message", type: "text", nullable: true),
                    notificationsyoutubelivechannel = table.Column<string>(name: "notifications.youtube.live.channel", type: "character varying(19)", nullable: true),
                    notificationsyoutubelivemessage = table.Column<string>(name: "notifications.youtube.live.message", type: "text", nullable: true),
                    suggestionsemojisupvote = table.Column<string>(name: "suggestions.emojis.upvote", type: "character varying(128)", maxLength: 128, nullable: false),
                    suggestionsemojisdownvote = table.Column<string>(name: "suggestions.emojis.downvote", type: "character varying(128)", maxLength: 128, nullable: false),
                    suggestionschannel = table.Column<string>(name: "suggestions.channel", type: "character varying(19)", maxLength: 19, nullable: true),
                    suggestionsonactiondm = table.Column<bool>(name: "suggestions.on-action.dm", type: "boolean", nullable: false),
                    suggestionsonactionrepost = table.Column<bool>(name: "suggestions.on-action.repost", type: "boolean", nullable: false),
                    suggestionsonactionhideauthor = table.Column<bool>(name: "suggestions.on-action.hide-author", type: "boolean", nullable: false),
                    eventsmemberusernameupdate = table.Column<bool>(name: "events.member-username-update", type: "boolean", nullable: false),
                    birthdaychannel = table.Column<string>(name: "birthday.channel", type: "character varying(19)", maxLength: 19, nullable: true),
                    birthdaymessage = table.Column<string>(name: "birthday.message", type: "character varying(200)", maxLength: 200, nullable: true),
                    birthdayrole = table.Column<string>(name: "birthday.role", type: "character varying(19)", maxLength: 19, nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_guilds", x => x.id);
                });

            migrationBuilder.CreateTable(
                name: "youtube_subscription",
                columns: table => new
                {
                    id = table.Column<string>(type: "character varying(24)", maxLength: 24, nullable: false),
                    already_seen_ids = table.Column<string[]>(type: "character varying(11)[]", nullable: false),
                    expires_at = table.Column<DateTime>(type: "timestamp without time zone", nullable: false),
                    guild_ids = table.Column<string[]>(type: "character varying(19)[]", nullable: false),
                    channel_title = table.Column<string>(type: "text", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_youtube_subscription", x => x.id);
                });
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "guilds");

            migrationBuilder.DropTable(
                name: "youtube_subscription");
        }
    }
}
