name: Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  DotNetCI:
    name: Dotnet Build & Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.x'
      - name: Restore CI Cache
        uses: actions/cache@v2.1.6
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
      - name: Build C# code
        run: dotnet build
      - name: Run C# unit tests
        run: dotnet test tests/UnitTests --collect:"XPlat Code Coverage" --settings coverlet.runsettings
      - name: Store code coverage report (Unit Tests)
        uses: actions/upload-artifact@v2
        with:
          name: dotnet-coverage-unit
          path: tests/UnitTests/TestResults/

  Upload_Coverage_Report:
    name: Upload coverage report to codecov
    needs: DotNetCI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - name: Download DotNet Unit Test Coverage report
        uses: actions/download-artifact@v2
        with:
          name: dotnet-coverage-unit
          path: tests/UnitTests/TestResults/
      - name: Codecov Upload
        uses: codecov/codecov-action@v2.0.2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
