name: Continuous Delivery

on:
  push:
    branches:
      - main
    paths:
      - 'sources/**'
      - 'Notifications.Dockerfile'
      - 'Cdn.Dockerfile'
      - '.github/workflows/continuous-delivery.yml'
      - 'README.md'

jobs:
  PublishNotifications:
    name: Publish Notifications image to GitHub Container Registry
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579 # renovate: tag=v2
        with:
          submodules: true
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@94ab11c41e45d028884a99163086648e898eed25 # renovate: tag=v1.6.0
      - name: Login to GitHub Container Registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9 # renovate: tag=v1.10.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push YouTube Notifications Docker image
        uses: docker/build-push-action@a66e35b9cbcf4ad0ea91ffcaf7bbad63ad9e0229 # renovate: tag=v2.7.0
        with:
          push: true
          context: .
          file: Notifications.Dockerfile
          tags: ghcr.io/skyra-project/arkadia.notifications:latest
      - name: Build and push CDN Docker image
        uses: docker/build-push-action@a66e35b9cbcf4ad0ea91ffcaf7bbad63ad9e0229 # renovate: tag=v2.7.0
        with:
          push: true
          context: .
          file: Cdn.Dockerfile
          tags: ghcr.io/skyra-project/arkadia.cdn:latest
